/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as DevGraphqlRouteImport } from './routes/dev.graphql'
import { Route as DevRuntimeRouteImport } from './routes/dev.runtime'
import { Route as PlaygroundAssemblyRouteImport } from './routes/playground.assembly'
import { Route as PlaygroundRetrievalRouteImport } from './routes/playground.retrieval'
import { Route as AssemblyFragmentsIndexRouteImport } from './routes/assembly.fragments.index'
import { Route as AssemblyFragmentsKeyRouteImport } from './routes/assembly.fragments.$key'
import { Route as AssemblySkillsIndexRouteImport } from './routes/assembly.skills.index'
import { Route as AssemblySkillsKeyRouteImport } from './routes/assembly.skills.$key'
import { Route as AssemblyTemplatesIndexRouteImport } from './routes/assembly.templates.index'
import { Route as AssemblyTemplatesKeyRouteImport } from './routes/assembly.templates.$key'
import { Route as AssemblyToolsIndexRouteImport } from './routes/assembly.tools.index'
import { Route as AssemblyToolsKeyRouteImport } from './routes/assembly.tools.$key'
import { Route as ExploreChunksIdRouteImport } from './routes/explore.chunks.$id'
import { Route as ExploreConceptsIndexRouteImport } from './routes/explore.concepts.index'
import { Route as ExploreConceptsKeyRouteImport } from './routes/explore.concepts.$key'
import { Route as ExploreDimensionsIndexRouteImport } from './routes/explore.dimensions.index'
import { Route as ExploreDimensionsKeyRouteImport } from './routes/explore.dimensions.$key'
import { Route as ExploreDomainsIndexRouteImport } from './routes/explore.domains.index'
import { Route as ExploreDomainsKeyRouteImport } from './routes/explore.domains.$key'
import { Route as ExploreKnowledgeIndexRouteImport } from './routes/explore.knowledge.index'
import { Route as ExploreKnowledgeKeyRouteImport } from './routes/explore.knowledge.$key'
import { Route as ExploreSelectionGroupsIndexRouteImport } from './routes/explore.selection-groups.index'
import { Route as ExploreSelectionGroupsKeyRouteImport } from './routes/explore.selection-groups.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGraphqlRoute = DevGraphqlRouteImport.update({
  id: '/dev/graphql',
  path: '/dev/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRuntimeRoute = DevRuntimeRouteImport.update({
  id: '/dev/runtime',
  path: '/dev/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundAssemblyRoute = PlaygroundAssemblyRouteImport.update({
  id: '/playground/assembly',
  path: '/playground/assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRetrievalRoute = PlaygroundRetrievalRouteImport.update({
  id: '/playground/retrieval',
  path: '/playground/retrieval',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyFragmentsIndexRoute = AssemblyFragmentsIndexRouteImport.update({
  id: '/assembly/fragments/',
  path: '/assembly/fragments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyFragmentsKeyRoute = AssemblyFragmentsKeyRouteImport.update({
  id: '/assembly/fragments/$key',
  path: '/assembly/fragments/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblySkillsIndexRoute = AssemblySkillsIndexRouteImport.update({
  id: '/assembly/skills/',
  path: '/assembly/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblySkillsKeyRoute = AssemblySkillsKeyRouteImport.update({
  id: '/assembly/skills/$key',
  path: '/assembly/skills/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyTemplatesIndexRoute = AssemblyTemplatesIndexRouteImport.update({
  id: '/assembly/templates/',
  path: '/assembly/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyTemplatesKeyRoute = AssemblyTemplatesKeyRouteImport.update({
  id: '/assembly/templates/$key',
  path: '/assembly/templates/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyToolsIndexRoute = AssemblyToolsIndexRouteImport.update({
  id: '/assembly/tools/',
  path: '/assembly/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyToolsKeyRoute = AssemblyToolsKeyRouteImport.update({
  id: '/assembly/tools/$key',
  path: '/assembly/tools/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreChunksIdRoute = ExploreChunksIdRouteImport.update({
  id: '/explore/chunks/$id',
  path: '/explore/chunks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreConceptsIndexRoute = ExploreConceptsIndexRouteImport.update({
  id: '/explore/concepts/',
  path: '/explore/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreConceptsKeyRoute = ExploreConceptsKeyRouteImport.update({
  id: '/explore/concepts/$key',
  path: '/explore/concepts/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDimensionsIndexRoute = ExploreDimensionsIndexRouteImport.update({
  id: '/explore/dimensions/',
  path: '/explore/dimensions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDimensionsKeyRoute = ExploreDimensionsKeyRouteImport.update({
  id: '/explore/dimensions/$key',
  path: '/explore/dimensions/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDomainsIndexRoute = ExploreDomainsIndexRouteImport.update({
  id: '/explore/domains/',
  path: '/explore/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreDomainsKeyRoute = ExploreDomainsKeyRouteImport.update({
  id: '/explore/domains/$key',
  path: '/explore/domains/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreKnowledgeIndexRoute = ExploreKnowledgeIndexRouteImport.update({
  id: '/explore/knowledge/',
  path: '/explore/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreKnowledgeKeyRoute = ExploreKnowledgeKeyRouteImport.update({
  id: '/explore/knowledge/$key',
  path: '/explore/knowledge/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSelectionGroupsIndexRoute =
  ExploreSelectionGroupsIndexRouteImport.update({
    id: '/explore/selection-groups/',
    path: '/explore/selection-groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExploreSelectionGroupsKeyRoute =
  ExploreSelectionGroupsKeyRouteImport.update({
    id: '/explore/selection-groups/$key',
    path: '/explore/selection-groups/$key',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graphql': typeof GraphqlRoute
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/dev/graphql': typeof DevGraphqlRoute
  '/dev/runtime': typeof DevRuntimeRoute
  '/playground/assembly': typeof PlaygroundAssemblyRoute
  '/playground/retrieval': typeof PlaygroundRetrievalRoute
  '/assembly/fragments/$key': typeof AssemblyFragmentsKeyRoute
  '/assembly/skills/$key': typeof AssemblySkillsKeyRoute
  '/assembly/templates/$key': typeof AssemblyTemplatesKeyRoute
  '/assembly/tools/$key': typeof AssemblyToolsKeyRoute
  '/explore/chunks/$id': typeof ExploreChunksIdRoute
  '/explore/concepts/$key': typeof ExploreConceptsKeyRoute
  '/explore/dimensions/$key': typeof ExploreDimensionsKeyRoute
  '/explore/domains/$key': typeof ExploreDomainsKeyRoute
  '/explore/knowledge/$key': typeof ExploreKnowledgeKeyRoute
  '/explore/selection-groups/$key': typeof ExploreSelectionGroupsKeyRoute
  '/assembly/fragments/': typeof AssemblyFragmentsIndexRoute
  '/assembly/skills/': typeof AssemblySkillsIndexRoute
  '/assembly/templates/': typeof AssemblyTemplatesIndexRoute
  '/assembly/tools/': typeof AssemblyToolsIndexRoute
  '/explore/concepts/': typeof ExploreConceptsIndexRoute
  '/explore/dimensions/': typeof ExploreDimensionsIndexRoute
  '/explore/domains/': typeof ExploreDomainsIndexRoute
  '/explore/knowledge/': typeof ExploreKnowledgeIndexRoute
  '/explore/selection-groups/': typeof ExploreSelectionGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphql': typeof GraphqlRoute
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/dev/graphql': typeof DevGraphqlRoute
  '/dev/runtime': typeof DevRuntimeRoute
  '/playground/assembly': typeof PlaygroundAssemblyRoute
  '/playground/retrieval': typeof PlaygroundRetrievalRoute
  '/assembly/fragments/$key': typeof AssemblyFragmentsKeyRoute
  '/assembly/skills/$key': typeof AssemblySkillsKeyRoute
  '/assembly/templates/$key': typeof AssemblyTemplatesKeyRoute
  '/assembly/tools/$key': typeof AssemblyToolsKeyRoute
  '/explore/chunks/$id': typeof ExploreChunksIdRoute
  '/explore/concepts/$key': typeof ExploreConceptsKeyRoute
  '/explore/dimensions/$key': typeof ExploreDimensionsKeyRoute
  '/explore/domains/$key': typeof ExploreDomainsKeyRoute
  '/explore/knowledge/$key': typeof ExploreKnowledgeKeyRoute
  '/explore/selection-groups/$key': typeof ExploreSelectionGroupsKeyRoute
  '/assembly/fragments': typeof AssemblyFragmentsIndexRoute
  '/assembly/skills': typeof AssemblySkillsIndexRoute
  '/assembly/templates': typeof AssemblyTemplatesIndexRoute
  '/assembly/tools': typeof AssemblyToolsIndexRoute
  '/explore/concepts': typeof ExploreConceptsIndexRoute
  '/explore/dimensions': typeof ExploreDimensionsIndexRoute
  '/explore/domains': typeof ExploreDomainsIndexRoute
  '/explore/knowledge': typeof ExploreKnowledgeIndexRoute
  '/explore/selection-groups': typeof ExploreSelectionGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graphql': typeof GraphqlRoute
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/dev/graphql': typeof DevGraphqlRoute
  '/dev/runtime': typeof DevRuntimeRoute
  '/playground/assembly': typeof PlaygroundAssemblyRoute
  '/playground/retrieval': typeof PlaygroundRetrievalRoute
  '/assembly/fragments/$key': typeof AssemblyFragmentsKeyRoute
  '/assembly/skills/$key': typeof AssemblySkillsKeyRoute
  '/assembly/templates/$key': typeof AssemblyTemplatesKeyRoute
  '/assembly/tools/$key': typeof AssemblyToolsKeyRoute
  '/explore/chunks/$id': typeof ExploreChunksIdRoute
  '/explore/concepts/$key': typeof ExploreConceptsKeyRoute
  '/explore/dimensions/$key': typeof ExploreDimensionsKeyRoute
  '/explore/domains/$key': typeof ExploreDomainsKeyRoute
  '/explore/knowledge/$key': typeof ExploreKnowledgeKeyRoute
  '/explore/selection-groups/$key': typeof ExploreSelectionGroupsKeyRoute
  '/assembly/fragments/': typeof AssemblyFragmentsIndexRoute
  '/assembly/skills/': typeof AssemblySkillsIndexRoute
  '/assembly/templates/': typeof AssemblyTemplatesIndexRoute
  '/assembly/tools/': typeof AssemblyToolsIndexRoute
  '/explore/concepts/': typeof ExploreConceptsIndexRoute
  '/explore/dimensions/': typeof ExploreDimensionsIndexRoute
  '/explore/domains/': typeof ExploreDomainsIndexRoute
  '/explore/knowledge/': typeof ExploreKnowledgeIndexRoute
  '/explore/selection-groups/': typeof ExploreSelectionGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graphql'
    | '/healthz'
    | '/readyz'
    | '/dev/graphql'
    | '/dev/runtime'
    | '/playground/assembly'
    | '/playground/retrieval'
    | '/assembly/fragments/$key'
    | '/assembly/skills/$key'
    | '/assembly/templates/$key'
    | '/assembly/tools/$key'
    | '/explore/chunks/$id'
    | '/explore/concepts/$key'
    | '/explore/dimensions/$key'
    | '/explore/domains/$key'
    | '/explore/knowledge/$key'
    | '/explore/selection-groups/$key'
    | '/assembly/fragments/'
    | '/assembly/skills/'
    | '/assembly/templates/'
    | '/assembly/tools/'
    | '/explore/concepts/'
    | '/explore/dimensions/'
    | '/explore/domains/'
    | '/explore/knowledge/'
    | '/explore/selection-groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graphql'
    | '/healthz'
    | '/readyz'
    | '/dev/graphql'
    | '/dev/runtime'
    | '/playground/assembly'
    | '/playground/retrieval'
    | '/assembly/fragments/$key'
    | '/assembly/skills/$key'
    | '/assembly/templates/$key'
    | '/assembly/tools/$key'
    | '/explore/chunks/$id'
    | '/explore/concepts/$key'
    | '/explore/dimensions/$key'
    | '/explore/domains/$key'
    | '/explore/knowledge/$key'
    | '/explore/selection-groups/$key'
    | '/assembly/fragments'
    | '/assembly/skills'
    | '/assembly/templates'
    | '/assembly/tools'
    | '/explore/concepts'
    | '/explore/dimensions'
    | '/explore/domains'
    | '/explore/knowledge'
    | '/explore/selection-groups'
  id:
    | '__root__'
    | '/'
    | '/graphql'
    | '/healthz'
    | '/readyz'
    | '/dev/graphql'
    | '/dev/runtime'
    | '/playground/assembly'
    | '/playground/retrieval'
    | '/assembly/fragments/$key'
    | '/assembly/skills/$key'
    | '/assembly/templates/$key'
    | '/assembly/tools/$key'
    | '/explore/chunks/$id'
    | '/explore/concepts/$key'
    | '/explore/dimensions/$key'
    | '/explore/domains/$key'
    | '/explore/knowledge/$key'
    | '/explore/selection-groups/$key'
    | '/assembly/fragments/'
    | '/assembly/skills/'
    | '/assembly/templates/'
    | '/assembly/tools/'
    | '/explore/concepts/'
    | '/explore/dimensions/'
    | '/explore/domains/'
    | '/explore/knowledge/'
    | '/explore/selection-groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphqlRoute: typeof GraphqlRoute
  HealthzRoute: typeof HealthzRoute
  ReadyzRoute: typeof ReadyzRoute
  DevGraphqlRoute: typeof DevGraphqlRoute
  DevRuntimeRoute: typeof DevRuntimeRoute
  PlaygroundAssemblyRoute: typeof PlaygroundAssemblyRoute
  PlaygroundRetrievalRoute: typeof PlaygroundRetrievalRoute
  AssemblyFragmentsKeyRoute: typeof AssemblyFragmentsKeyRoute
  AssemblySkillsKeyRoute: typeof AssemblySkillsKeyRoute
  AssemblyTemplatesKeyRoute: typeof AssemblyTemplatesKeyRoute
  AssemblyToolsKeyRoute: typeof AssemblyToolsKeyRoute
  ExploreChunksIdRoute: typeof ExploreChunksIdRoute
  ExploreConceptsKeyRoute: typeof ExploreConceptsKeyRoute
  ExploreDimensionsKeyRoute: typeof ExploreDimensionsKeyRoute
  ExploreDomainsKeyRoute: typeof ExploreDomainsKeyRoute
  ExploreKnowledgeKeyRoute: typeof ExploreKnowledgeKeyRoute
  ExploreSelectionGroupsKeyRoute: typeof ExploreSelectionGroupsKeyRoute
  AssemblyFragmentsIndexRoute: typeof AssemblyFragmentsIndexRoute
  AssemblySkillsIndexRoute: typeof AssemblySkillsIndexRoute
  AssemblyTemplatesIndexRoute: typeof AssemblyTemplatesIndexRoute
  AssemblyToolsIndexRoute: typeof AssemblyToolsIndexRoute
  ExploreConceptsIndexRoute: typeof ExploreConceptsIndexRoute
  ExploreDimensionsIndexRoute: typeof ExploreDimensionsIndexRoute
  ExploreDomainsIndexRoute: typeof ExploreDomainsIndexRoute
  ExploreKnowledgeIndexRoute: typeof ExploreKnowledgeIndexRoute
  ExploreSelectionGroupsIndexRoute: typeof ExploreSelectionGroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/graphql': {
      id: '/dev/graphql'
      path: '/dev/graphql'
      fullPath: '/dev/graphql'
      preLoaderRoute: typeof DevGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/runtime': {
      id: '/dev/runtime'
      path: '/dev/runtime'
      fullPath: '/dev/runtime'
      preLoaderRoute: typeof DevRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/assembly': {
      id: '/playground/assembly'
      path: '/playground/assembly'
      fullPath: '/playground/assembly'
      preLoaderRoute: typeof PlaygroundAssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/retrieval': {
      id: '/playground/retrieval'
      path: '/playground/retrieval'
      fullPath: '/playground/retrieval'
      preLoaderRoute: typeof PlaygroundRetrievalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/fragments/': {
      id: '/assembly/fragments/'
      path: '/assembly/fragments'
      fullPath: '/assembly/fragments/'
      preLoaderRoute: typeof AssemblyFragmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/fragments/$key': {
      id: '/assembly/fragments/$key'
      path: '/assembly/fragments/$key'
      fullPath: '/assembly/fragments/$key'
      preLoaderRoute: typeof AssemblyFragmentsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/skills/': {
      id: '/assembly/skills/'
      path: '/assembly/skills'
      fullPath: '/assembly/skills/'
      preLoaderRoute: typeof AssemblySkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/skills/$key': {
      id: '/assembly/skills/$key'
      path: '/assembly/skills/$key'
      fullPath: '/assembly/skills/$key'
      preLoaderRoute: typeof AssemblySkillsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/templates/': {
      id: '/assembly/templates/'
      path: '/assembly/templates'
      fullPath: '/assembly/templates/'
      preLoaderRoute: typeof AssemblyTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/templates/$key': {
      id: '/assembly/templates/$key'
      path: '/assembly/templates/$key'
      fullPath: '/assembly/templates/$key'
      preLoaderRoute: typeof AssemblyTemplatesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/tools/': {
      id: '/assembly/tools/'
      path: '/assembly/tools'
      fullPath: '/assembly/tools/'
      preLoaderRoute: typeof AssemblyToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/tools/$key': {
      id: '/assembly/tools/$key'
      path: '/assembly/tools/$key'
      fullPath: '/assembly/tools/$key'
      preLoaderRoute: typeof AssemblyToolsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/chunks/$id': {
      id: '/explore/chunks/$id'
      path: '/explore/chunks/$id'
      fullPath: '/explore/chunks/$id'
      preLoaderRoute: typeof ExploreChunksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/concepts/': {
      id: '/explore/concepts/'
      path: '/explore/concepts'
      fullPath: '/explore/concepts/'
      preLoaderRoute: typeof ExploreConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/concepts/$key': {
      id: '/explore/concepts/$key'
      path: '/explore/concepts/$key'
      fullPath: '/explore/concepts/$key'
      preLoaderRoute: typeof ExploreConceptsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/dimensions/': {
      id: '/explore/dimensions/'
      path: '/explore/dimensions'
      fullPath: '/explore/dimensions/'
      preLoaderRoute: typeof ExploreDimensionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/dimensions/$key': {
      id: '/explore/dimensions/$key'
      path: '/explore/dimensions/$key'
      fullPath: '/explore/dimensions/$key'
      preLoaderRoute: typeof ExploreDimensionsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/domains/': {
      id: '/explore/domains/'
      path: '/explore/domains'
      fullPath: '/explore/domains/'
      preLoaderRoute: typeof ExploreDomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/domains/$key': {
      id: '/explore/domains/$key'
      path: '/explore/domains/$key'
      fullPath: '/explore/domains/$key'
      preLoaderRoute: typeof ExploreDomainsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/knowledge/': {
      id: '/explore/knowledge/'
      path: '/explore/knowledge'
      fullPath: '/explore/knowledge/'
      preLoaderRoute: typeof ExploreKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/knowledge/$key': {
      id: '/explore/knowledge/$key'
      path: '/explore/knowledge/$key'
      fullPath: '/explore/knowledge/$key'
      preLoaderRoute: typeof ExploreKnowledgeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/selection-groups/': {
      id: '/explore/selection-groups/'
      path: '/explore/selection-groups'
      fullPath: '/explore/selection-groups/'
      preLoaderRoute: typeof ExploreSelectionGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/selection-groups/$key': {
      id: '/explore/selection-groups/$key'
      path: '/explore/selection-groups/$key'
      fullPath: '/explore/selection-groups/$key'
      preLoaderRoute: typeof ExploreSelectionGroupsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphqlRoute: GraphqlRoute,
  HealthzRoute: HealthzRoute,
  ReadyzRoute: ReadyzRoute,
  DevGraphqlRoute: DevGraphqlRoute,
  DevRuntimeRoute: DevRuntimeRoute,
  PlaygroundAssemblyRoute: PlaygroundAssemblyRoute,
  PlaygroundRetrievalRoute: PlaygroundRetrievalRoute,
  AssemblyFragmentsKeyRoute: AssemblyFragmentsKeyRoute,
  AssemblySkillsKeyRoute: AssemblySkillsKeyRoute,
  AssemblyTemplatesKeyRoute: AssemblyTemplatesKeyRoute,
  AssemblyToolsKeyRoute: AssemblyToolsKeyRoute,
  ExploreChunksIdRoute: ExploreChunksIdRoute,
  ExploreConceptsKeyRoute: ExploreConceptsKeyRoute,
  ExploreDimensionsKeyRoute: ExploreDimensionsKeyRoute,
  ExploreDomainsKeyRoute: ExploreDomainsKeyRoute,
  ExploreKnowledgeKeyRoute: ExploreKnowledgeKeyRoute,
  ExploreSelectionGroupsKeyRoute: ExploreSelectionGroupsKeyRoute,
  AssemblyFragmentsIndexRoute: AssemblyFragmentsIndexRoute,
  AssemblySkillsIndexRoute: AssemblySkillsIndexRoute,
  AssemblyTemplatesIndexRoute: AssemblyTemplatesIndexRoute,
  AssemblyToolsIndexRoute: AssemblyToolsIndexRoute,
  ExploreConceptsIndexRoute: ExploreConceptsIndexRoute,
  ExploreDimensionsIndexRoute: ExploreDimensionsIndexRoute,
  ExploreDomainsIndexRoute: ExploreDomainsIndexRoute,
  ExploreKnowledgeIndexRoute: ExploreKnowledgeIndexRoute,
  ExploreSelectionGroupsIndexRoute: ExploreSelectionGroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
