/**
 * Stable diagnostic and error codes — spec/14-diagnostic-error-code-registry.md.
 * Closed v1 vocabulary; never invent synonymous strings.
 */

export const SourceErrorCode = {
  SOURCE_PARSE_ERROR: "SOURCE_PARSE_ERROR",
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_FIELD_TYPE: "INVALID_FIELD_TYPE",
  DUPLICATE_ID: "DUPLICATE_ID",
  DUPLICATE_KEY: "DUPLICATE_KEY",
  REFERENCE_NOT_FOUND: "REFERENCE_NOT_FOUND",
  REFERENCE_TYPE_MISMATCH: "REFERENCE_TYPE_MISMATCH",
  INVALID_EXPRESSION: "INVALID_EXPRESSION",
  INVALID_OPERATOR_FOR_DIMENSION: "INVALID_OPERATOR_FOR_DIMENSION",
  UNKNOWN_DIMENSION: "UNKNOWN_DIMENSION",
  DIMENSION_VALUE_NOT_FOUND: "DIMENSION_VALUE_NOT_FOUND",
  UNSAFE_AUTHORIZATION_MISSING_BEHAVIOR: "UNSAFE_AUTHORIZATION_MISSING_BEHAVIOR",
  HIERARCHY_CYCLE: "HIERARCHY_CYCLE",
  TOOL_DEPENDENCY_CYCLE: "TOOL_DEPENDENCY_CYCLE",
  TOOL_SELF_DEPENDENCY: "TOOL_SELF_DEPENDENCY",
  SELECTION_GROUP_TYPE_MISMATCH: "SELECTION_GROUP_TYPE_MISMATCH",
  INVALID_LIFECYCLE_DEPENDENCY: "INVALID_LIFECYCLE_DEPENDENCY",
  DUPLICATE_HEADING_ID: "DUPLICATE_HEADING_ID",
  DUPLICATE_DERIVED_CHUNK_KEY: "DUPLICATE_DERIVED_CHUNK_KEY",
  EMBEDDING_DIMENSION_MISMATCH: "EMBEDDING_DIMENSION_MISMATCH",
  EVAL_SCHEMA_INVALID: "EVAL_SCHEMA_INVALID",
} as const;

export const RuntimeErrorCode = {
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_CONTEXT: "INVALID_CONTEXT",
  UNKNOWN_CONTEXT_DIMENSION: "UNKNOWN_CONTEXT_DIMENSION",
  CONTEXT_TYPE_MISMATCH: "CONTEXT_TYPE_MISMATCH",
  CONTEXT_ENUM_VALUE_UNKNOWN: "CONTEXT_ENUM_VALUE_UNKNOWN",
  REQUIRED_CONTEXT_DIMENSION_MISSING: "REQUIRED_CONTEXT_DIMENSION_MISSING",
  CONTEXT_DIMENSION_NOT_CLIENT_SETTABLE: "CONTEXT_DIMENSION_NOT_CLIENT_SETTABLE",
  NAMESPACE_NOT_FOUND: "NAMESPACE_NOT_FOUND",
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  TEMPLATE_NOT_PUBLISHED: "TEMPLATE_NOT_PUBLISHED",
  AUTHORIZATION_EVALUATION_FAILED: "AUTHORIZATION_EVALUATION_FAILED",
  ASSEMBLY_REQUIREMENT_UNSATISFIED: "ASSEMBLY_REQUIREMENT_UNSATISFIED",
  ASSEMBLY_BUDGET_EXCEEDED: "ASSEMBLY_BUDGET_EXCEEDED",
  EMBEDDING_UNAVAILABLE: "EMBEDDING_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export const RetrievalExclusionCode = {
  LIFECYCLE_NOT_PUBLISHED: "LIFECYCLE_NOT_PUBLISHED",
  OUTSIDE_EFFECTIVE_WINDOW: "OUTSIDE_EFFECTIVE_WINDOW",
  AUTHORIZATION_NO_MATCH: "AUTHORIZATION_NO_MATCH",
  APPLICABILITY_NO_MATCH: "APPLICABILITY_NO_MATCH",
  SELECTION_GROUP_NOT_SELECTED: "SELECTION_GROUP_NOT_SELECTED",
  PACKING_ITEM_CAP: "PACKING_ITEM_CAP",
  PACKING_TOKEN_BUDGET: "PACKING_TOKEN_BUDGET",
} as const;

export const AssemblyCode = {
  RUNTIME_BINDING_UNAVAILABLE: "RUNTIME_BINDING_UNAVAILABLE",
  REQUIRED_DEPENDENCY_UNAVAILABLE: "REQUIRED_DEPENDENCY_UNAVAILABLE",
  SKILL_REQUIRED_TOOL_UNAVAILABLE: "SKILL_REQUIRED_TOOL_UNAVAILABLE",
  OPTIONAL_DEPENDENCY_OMITTED: "OPTIONAL_DEPENDENCY_OMITTED",
  TASK_REQUIRED_FOR_FRAGMENT: "TASK_REQUIRED_FOR_FRAGMENT",
} as const;

export const WarningCode = {
  VECTOR_CHANNEL_UNAVAILABLE: "VECTOR_CHANNEL_UNAVAILABLE",
  ONTOLOGY_CHANNEL_UNAVAILABLE: "ONTOLOGY_CHANNEL_UNAVAILABLE",
  OPTIONAL_TOOL_DEPENDENCY_UNAVAILABLE: "OPTIONAL_TOOL_DEPENDENCY_UNAVAILABLE",
  TOKEN_COUNT_APPROXIMATE: "TOKEN_COUNT_APPROXIMATE",
  AMBIGUOUS_EXACT_LEXICAL_MATCH: "AMBIGUOUS_EXACT_LEXICAL_MATCH",
  SUSPICIOUS_DIMENSION_CATEGORY_USAGE: "SUSPICIOUS_DIMENSION_CATEGORY_USAGE",
} as const;

export const RetrievalReasonCode = {
  VECTOR_MATCH: "VECTOR_MATCH",
  FULL_TEXT_MATCH: "FULL_TEXT_MATCH",
  TRIGRAM_MATCH: "TRIGRAM_MATCH",
  DIRECT_CONCEPT_LINK: "DIRECT_CONCEPT_LINK",
  ONTOLOGY_CONCEPT_LINK: "ONTOLOGY_CONCEPT_LINK",
} as const;

export const AssemblyReasonCode = {
  TEMPLATE_FRAGMENT: "TEMPLATE_FRAGMENT",
  APPLICABLE_FRAGMENT: "APPLICABLE_FRAGMENT",
  TASK_RELEVANT_FRAGMENT: "TASK_RELEVANT_FRAGMENT",
  SELECTED_SKILL: "SELECTED_SKILL",
  SKILL_REQUIRED_TOOL: "SKILL_REQUIRED_TOOL",
  DIRECT_TASK_TOOL: "DIRECT_TASK_TOOL",
  REQUIRED_TOOL_DEPENDENCY: "REQUIRED_TOOL_DEPENDENCY",
  OPTIONAL_TOOL_DEPENDENCY: "OPTIONAL_TOOL_DEPENDENCY",
} as const;

/** Retrieval stage names (spec/14) */
export const RetrievalStage = {
  CONTEXT_VALIDATION: "context_validation",
  QUERY_NORMALIZATION: "query_normalization",
  QUERY_EMBEDDING: "query_embedding",
  CONCEPT_RESOLUTION: "concept_resolution",
  VECTOR_CANDIDATES: "vector_candidates",
  FTS_CANDIDATES: "fts_candidates",
  TRIGRAM_CANDIDATES: "trigram_candidates",
  CONCEPT_LINKED_CANDIDATES: "concept_linked_candidates",
  ONTOLOGY_CANDIDATES: "ontology_candidates",
  CANDIDATE_MERGE: "candidate_merge",
  LIFECYCLE_FILTER: "lifecycle_filter",
  AUTHORIZATION: "authorization",
  APPLICABILITY: "applicability",
  SELECTION_GROUPS: "selection_groups",
  RRF_FUSION: "rrf_fusion",
  FINAL_ORDERING: "final_ordering",
  PACKING: "packing",
} as const;

/** Agent Assembly stage names (spec/14) */
export const AssemblyStage = {
  TEMPLATE_RESOLUTION: "template_resolution",
  CONTEXT_VALIDATION: "context_validation",
  TASK_EMBEDDING: "task_embedding",
  TASK_CONCEPT_RESOLUTION: "task_concept_resolution",
  SKILL_DISCOVERY: "skill_discovery",
  FRAGMENT_DISCOVERY: "fragment_discovery",
  TOOL_DISCOVERY: "tool_discovery",
  ASSEMBLY_FILTERING: "assembly_filtering",
  SELECTION_GROUPS: "selection_groups",
  SKILL_SELECTION: "skill_selection",
  DEPENDENCY_CLOSURE: "dependency_closure",
  BOOTSTRAP_RETRIEVAL: "bootstrap_retrieval",
  BUDGET_APPLICATION: "budget_application",
  PROMPT_RENDERING: "prompt_rendering",
} as const;

export type SourceErrorCode = (typeof SourceErrorCode)[keyof typeof SourceErrorCode];
export type RuntimeErrorCode = (typeof RuntimeErrorCode)[keyof typeof RuntimeErrorCode];
export type RetrievalExclusionCode =
  (typeof RetrievalExclusionCode)[keyof typeof RetrievalExclusionCode];
export type AssemblyCode = (typeof AssemblyCode)[keyof typeof AssemblyCode];
export type WarningCode = (typeof WarningCode)[keyof typeof WarningCode];
export type RetrievalReasonCode = (typeof RetrievalReasonCode)[keyof typeof RetrievalReasonCode];
export type AssemblyReasonCode = (typeof AssemblyReasonCode)[keyof typeof AssemblyReasonCode];
export type RetrievalStage = (typeof RetrievalStage)[keyof typeof RetrievalStage];
export type AssemblyStage = (typeof AssemblyStage)[keyof typeof AssemblyStage];

/** Every stable diagnostic code in the closed v1 registry (spec/14). */
export type DiagnosticCode =
  | SourceErrorCode
  | RuntimeErrorCode
  | RetrievalExclusionCode
  | AssemblyCode
  | WarningCode;
