/**
 * Explorer GraphQL operations over the locked SDL (`graphql/schema.graphql`).
 * Each document is annotated `TypedDocumentNode<Query, Variables>` — the types
 * are generated by GraphQL Code Generator from these literals
 * (`bun run codegen` in packages/graphql), so `client.query(DOC)` returns
 * typed data; no hand-mirrored result types, no unchecked casts (spec/15).
 */
import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { gql } from "urql";
import type * as Ops from "../generated/operations";

// Shared source-location selection — one definition, spread into every
// document that fetches `source` (graphql-tag pluck resolves the
// interpolation for codegen; graphql-tag splices the doc at runtime).
export const SOURCE_FIELDS = gql`
  fragment SourceFields on SourceLocation {
    path
    line
    repositoryUrl
    repositoryRef
    viewUrl
  }
`;

// Shared row/prop types are indexed off the generated operation results —
// a component's contract is checked structurally against the real payload,
// so a field renamed in the SDL fails here, not at runtime.
export type EntityRefT = Ops.SimulateGatesQuery["simulateGates"]["entity"];
export type SourceLoc = Ops.ConceptsQuery["concepts"]["nodes"][number]["source"];
export type PageInfoT = Ops.ConceptsQuery["concepts"]["pageInfo"];
export type RuntimeInfoT = Ops.RuntimeInfoQuery["runtimeInfo"];

export const RUNTIME_INFO: TypedDocumentNode<Ops.RuntimeInfoQuery, Ops.RuntimeInfoQueryVariables> =
  gql`
  query RuntimeInfo {
    runtimeInfo {
      namespace { id key }
      environment
      runtimeRevision
      gitCommit
      sourceHash
      compilerVersion
    }
  }
`;

export type ConceptT = Ops.ConceptsQuery["concepts"]["nodes"][number];

export const CONCEPTS: TypedDocumentNode<Ops.ConceptsQuery, Ops.ConceptsQueryVariables> = gql`
  query Concepts($input: ConceptsInput) {
    concepts(input: $input) {
      nodes { id key name type description status
      domains { id key name }
      aliases { id alias }
      source { ...SourceFields }
      metadata }
      pageInfo { hasNextPage endCursor }
      totalCount
    }
  }

${SOURCE_FIELDS}
`;

export const CONCEPT: TypedDocumentNode<Ops.ConceptQuery, Ops.ConceptQueryVariables> = gql`
  query Concept($ref: EntityRefInput!) {
    concept(ref: $ref) {
      id key name type description status
      domains { id key name }
      aliases { id alias }
      source { ...SourceFields }
      metadata
      outgoingRelations { nodes { id type { key name } targetConcept { id key name } source { ...SourceFields } } totalCount }
      incomingRelations { nodes { id type { key name } sourceConcept { id key name } } totalCount }
    }
  }

${SOURCE_FIELDS}
`;

export const NEIGHBORHOOD: TypedDocumentNode<
  Ops.NeighborhoodQuery,
  Ops.NeighborhoodQueryVariables
> = gql`
  query Neighborhood($input: OntologyNeighborhoodInput!) {
    ontologyNeighborhood(input: $input) {
      center { id key name type status }
      concepts { id key name type status }
      relations { id type { key name } sourceConcept { id key name } targetConcept { id key name } }
      chunks { id key heading status knowledgeItem { key title } }
    }
  }
`;

export type NeighborhoodT = Ops.NeighborhoodQuery["ontologyNeighborhood"];

export const KNOWLEDGE_ITEMS: TypedDocumentNode<
  Ops.KnowledgeItemsQuery,
  Ops.KnowledgeItemsQueryVariables
> = gql`
  query KnowledgeItems($input: KnowledgeItemsInput) {
    knowledgeItems(input: $input) {
      nodes { id key title summary status authorityScore effectiveFrom effectiveTo source { ...SourceFields } }
      pageInfo { hasNextPage endCursor }
      totalCount
    }
  }

${SOURCE_FIELDS}
`;

export const KNOWLEDGE_ITEM: TypedDocumentNode<
  Ops.KnowledgeItemQuery,
  Ops.KnowledgeItemQueryVariables
> = gql`
  query KnowledgeItem($ref: EntityRefInput!) {
    knowledgeItem(ref: $ref) {
      id key title summary status authorityScore effectiveFrom effectiveTo metadata source { ...SourceFields }
      chunks { nodes { id key ordinal heading status priority tokenCount source { ...SourceFields } } totalCount }
      sourceReference { id key title uri type }
    }
  }

${SOURCE_FIELDS}
`;

export const KNOWLEDGE_CHUNK: TypedDocumentNode<
  Ops.KnowledgeChunkQuery,
  Ops.KnowledgeChunkQueryVariables
> = gql`
  query KnowledgeChunk($ref: KnowledgeChunkRefInput!) {
    knowledgeChunk(ref: $ref) {
      id key ordinal heading content status priority authorityScore tokenCount
      effectiveFrom effectiveTo
      authorization applicability
      knowledgeItem { id key title }
      concepts { id key name }
      selectionGroup { id key }
      metadata source { ...SourceFields }
    }
  }

${SOURCE_FIELDS}
`;

export const DOMAINS: TypedDocumentNode<Ops.DomainsQuery, Ops.DomainsQueryVariables> = gql`
  query Domains($input: DomainsInput) {
    domains(input: $input) {
      nodes { id key name description metadata source { ...SourceFields } }
      pageInfo { hasNextPage endCursor }
      totalCount
    }
  }

${SOURCE_FIELDS}
`;

// No singular `domain`/`selectionGroup` query exists in the SDL — detail
// pages pick the row from the unpaginated lists and fetch backlinks via
// filtered connections.

export const DIMENSIONS: TypedDocumentNode<Ops.DimensionsQuery, Ops.DimensionsQueryVariables> = gql`
  query Dimensions {
    dimensions {
      id key name description valueType cardinality category
      allowedOperators hierarchical required missingValueBehavior trust
      values(first: 200) { nodes { key name } }
      usedBy { entity { id } kind }
      source { ...SourceFields }
    }
  }

${SOURCE_FIELDS}
`;

export const DIMENSION: TypedDocumentNode<Ops.DimensionQuery, Ops.DimensionQueryVariables> = gql`
  query Dimension($ref: EntityRefInput!, $valuesAfter: String) {
    dimension(ref: $ref) {
      id key name description valueType cardinality category
      allowedOperators hierarchical required missingValueBehavior trust
      source { ...SourceFields }
      usedBy { entity { id key type } kind }
      values(first: 200, after: $valuesAfter) {
        nodes { id key name parent { id } children { id key } metadata }
        pageInfo { hasNextPage endCursor }
        totalCount
      }
    }
  }

${SOURCE_FIELDS}
`;

export const SELECTION_GROUPS: TypedDocumentNode<
  Ops.SelectionGroupsQuery,
  Ops.SelectionGroupsQueryVariables
> = gql`
  query SelectionGroups {
    selectionGroups {
      id key name entityType mode
      source { ...SourceFields }
      members { __typename ... on Skill { id key name priority } ... on Tool { id key name priority }
        ... on PromptFragment { id key name priority } ... on KnowledgeChunk { id key priority } }
    }
  }

${SOURCE_FIELDS}
`;

// ---------------------------------------------------------------------------
// Agent Assembly browse
// ---------------------------------------------------------------------------

export const TEMPLATES: TypedDocumentNode<
  Ops.AgentTemplatesQuery,
  Ops.AgentTemplatesQueryVariables
> = gql`
  query AgentTemplates {
    agentTemplates {
      id key name description status
      budgets { maxSkills maxTools promptTokens bootstrapKnowledgeTokens }
      retrievalProfile { id key }
      promptFragments { id key name section inclusionMode order }
      source { ...SourceFields } metadata
    }
  }

${SOURCE_FIELDS}
`;

export const TEMPLATE: TypedDocumentNode<Ops.AgentTemplateQuery, Ops.AgentTemplateQueryVariables> =
  gql`
  query AgentTemplate($ref: EntityRefInput!) {
    agentTemplate(ref: $ref) {
      id key name description status
      budgets { maxSkills maxTools promptTokens bootstrapKnowledgeTokens }
      retrievalProfile { id key name }
      promptFragments { id key name section inclusionMode order status }
      source { ...SourceFields } metadata
    }
  }

${SOURCE_FIELDS}
`;

export const SKILLS: TypedDocumentNode<Ops.SkillsQuery, Ops.SkillsQueryVariables> = gql`
  query Skills($input: SkillsInput) {
    skills(input: $input) {
      nodes { id key name description status priority
        selectionGroup { id key }
        concepts { id key }
        tools { id key name }
        promptFragments { id key }
        source { ...SourceFields } }
      pageInfo { hasNextPage endCursor }
      totalCount
    }
  }

${SOURCE_FIELDS}
`;

export const SKILL: TypedDocumentNode<Ops.SkillQuery, Ops.SkillQueryVariables> = gql`
  query Skill($ref: EntityRefInput!) {
    skill(ref: $ref) {
      id key name description status priority
      authorization applicability
      selectionGroup { id key name mode }
      concepts { id key name }
      promptFragments { id key name section }
      tools { id key name }
      source { ...SourceFields } metadata
    }
  }

${SOURCE_FIELDS}
`;

export const TOOLS: TypedDocumentNode<Ops.ToolsQuery, Ops.ToolsQueryVariables> = gql`
  query Tools($input: ToolsInput) {
    tools(input: $input) {
      nodes { id key name description status priority runtimeBinding risk latency
        selectionGroup { id key } concepts { id key } source { ...SourceFields } }
      pageInfo { hasNextPage endCursor }
      totalCount
    }
  }

${SOURCE_FIELDS}
`;

export const TOOL: TypedDocumentNode<Ops.ToolQuery, Ops.ToolQueryVariables> = gql`
  query Tool($ref: EntityRefInput!) {
    tool(ref: $ref) {
      id key name description status priority runtimeBinding risk latency
      authorization applicability
      selectionGroup { id key name mode }
      concepts { id key name }
      dependencies { requirement targetTool { id key name status } }
      dependents { requirement sourceTool { id key name status } }
      usedBy { id key type }
      inputSchema outputSchema
      source { ...SourceFields } metadata
    }
  }

${SOURCE_FIELDS}
`;

export const FRAGMENTS: TypedDocumentNode<
  Ops.PromptFragmentsQuery,
  Ops.PromptFragmentsQueryVariables
> = gql`
  query PromptFragments($input: PromptFragmentsInput) {
    promptFragments(input: $input) {
      nodes { id key name status inclusionMode section order priority
        selectionGroup { id key } concepts { id key } source { ...SourceFields } }
      pageInfo { hasNextPage endCursor }
      totalCount
    }
  }

${SOURCE_FIELDS}
`;

export const FRAGMENT: TypedDocumentNode<
  Ops.PromptFragmentQuery,
  Ops.PromptFragmentQueryVariables
> = gql`
  query PromptFragment($ref: EntityRefInput!) {
    promptFragment(ref: $ref) {
      id key name status inclusionMode section order priority content
      authorization applicability
      selectionGroup { id key name mode }
      concepts { id key name }
      usedBy { id key type }
      source { ...SourceFields } metadata
    }
  }

${SOURCE_FIELDS}
`;

// ---------------------------------------------------------------------------
// Playgrounds + simulation + search
// ---------------------------------------------------------------------------

export const RETRIEVE: TypedDocumentNode<Ops.RetrieveQuery, Ops.RetrieveQueryVariables> = gql`
  query Retrieve($input: RetrievalInput!) {
    retrieve(input: $input) {
      namespace { key } runtimeRevision query
      resolvedConcepts { concept { id key name } matchType matchedText score rank }
      results { score rank reasons { code message }
        chunk { id key heading ordinal knowledgeItem { key title } } }
      packedContext { estimatedTokens maxTokens maxChunks chunks { id key } }
      diagnostics {
        timings { stage milliseconds }
        candidateCounts { vector fullText trigram conceptLinked graphLinked unique
          afterLifecycle afterAuthorization afterApplicability afterSelectionGroups packed }
        exclusions { stage code message redacted chunk { id key type } }
        rankings { chunkId finalRank vectorRank vectorScore fullTextRank fullTextScore
          trigramRank trigramScore conceptRank graphRank rrfScore authorityScore priority }
        graphPaths { depth seedConcept { key } targetConcept { key }
          steps { relation { key } direction from { key } to { key } } }
        packing { considered packed skippedForBudget skippedForItemCap }
        warnings { code message }
        errors { code message }
      }
    }
  }
`;

export const ASSEMBLE: TypedDocumentNode<Ops.AssembleQuery, Ops.AssembleQueryVariables> = gql`
  query Assemble($input: AgentAssemblyInput!) {
    assembleAgent(input: $input) {
      namespace { key } runtimeRevision contextHash renderedPrompt
      template { id key name }
      task { text hash resolvedConcepts { concept { key name } matchType rank } }
      promptFragments { renderedOrder estimatedTokens sources
        fragment { id key name section inclusionMode }
        inclusionReasons { code message } }
      skills { rank score skill { id key name }
        inclusionReasons { code message } }
      tools { sources tool { id key name runtimeBinding }
        requiredBy { id key type } inclusionReasons { code message } }
      bootstrapKnowledge { score rank chunk { id key heading knowledgeItem { key } } }
      budgetUsage { skills maxSkills tools maxTools promptTokens maxPromptTokens
        bootstrapKnowledgeTokens maxBootstrapKnowledgeTokens }
      diagnostics {
        timings { stage milliseconds }
        warnings { code message }
        errors { code message }
        skillCandidates { entity { id key type } selected rank score code message
          causes { entityType entityId code message } }
        toolCandidates { entity { id key type } selected rank score code message
          causes { entityType entityId code message } }
        fragmentCandidates { entity { id key type } selected rank score code message
          causes { entityType entityId code message } }
        dependencyResolutions { requirement status reason
          sourceTool { key } targetTool { key } }
        bootstrapRetrieval {
          timings { stage milliseconds }
          candidateCounts { unique afterLifecycle afterAuthorization
            afterApplicability afterSelectionGroups packed }
          warnings { code message }
          errors { code message }
        }
      }
    }
  }
`;

export const SIMULATE_GATES: TypedDocumentNode<
  Ops.SimulateGatesQuery,
  Ops.SimulateGatesQueryVariables
> = gql`
  query SimulateGates($input: GateSimulationInput!) {
    simulateGates(input: $input) {
      entity { id key type }
      authorization { state eligible specificity diagnostics { code message } }
      applicability { state eligible specificity diagnostics { code message } }
    }
  }
`;

/** Global command-palette search — one request per entity type, keyed lists. */
export const GLOBAL_SEARCH: TypedDocumentNode<
  Ops.GlobalSearchQuery,
  Ops.GlobalSearchQueryVariables
> = gql`
  query GlobalSearch($q: String!) {
    concepts(input: {search: $q, first: 5}) { nodes { id key name status } }
    knowledgeItems(input: {search: $q, first: 5}) { nodes { id key title status } }
    domains(input: {search: $q, first: 5}) { nodes { id key name } }
    skills(input: {search: $q, first: 5}) { nodes { id key name status } }
    tools(input: {search: $q, first: 5}) { nodes { id key name status } }
    promptFragments(input: {search: $q, first: 5}) { nodes { id key name status } }
    agentTemplates { id key name status }
    selectionGroups { id key entityType mode }
    dimensions { id key name }
    retrievalProfiles { id key name }
    namespace { id key name }
  }
`;

export const RETRIEVAL_PROFILES: TypedDocumentNode<
  Ops.RetrievalProfilesQuery,
  Ops.RetrievalProfilesQueryVariables
> = gql`
  query RetrievalProfiles {
    retrievalProfiles { id key name config source { ...SourceFields } }
  }

${SOURCE_FIELDS}
`;

export const OVERVIEW: TypedDocumentNode<Ops.OverviewQuery, Ops.OverviewQueryVariables> = gql`
  query Overview {
    runtimeInfo {
      namespace { id key }
      environment
      runtimeRevision
      gitCommit
      sourceHash
      compilerVersion
    }
    concepts { totalCount }
    knowledgeItems { totalCount }
    domains { totalCount }
    skills { totalCount }
    tools { totalCount }
    promptFragments { totalCount }
    dimensions { id }
    selectionGroups { id }
    agentTemplates { id }
    retrievalProfiles { id }
  }
`;

export const NAMESPACE: TypedDocumentNode<Ops.NamespaceQuery, Ops.NamespaceQueryVariables> = gql`
  query Namespace($key: String) {
    namespace(key: $key) {
      id key name description
      defaultRetrievalProfile { id key name }
      metadata
    }
  }
`;
