import { cacheExchange } from "@urql/exchange-graphcache";
import type { IntrospectionQuery } from "graphql";
import { type Client, createClient, fetchExchange, type SSRExchange, ssrExchange } from "urql";
import schemaJson from "../generated/schema.json";

/**
 * urql + Graphcache + SSR exchange (spec/10 locked client stack, spec/15).
 * A fresh instance is created per SSR request inside `getRouter()` — the
 * normalized cache and in-flight dedup state are therefore never shared
 * between requests.
 */
export type ExplorerClient = {
  client: Client;
  ssr: SSRExchange;
};

export function createExplorerClient(opts: {
  /** Absolute origin for SSR fetch ("/graphql" is a route on this server). */
  origin?: string;
  /** Auth-bearing headers forwarded from the incoming request (SSR only). */
  headers?: Record<string, string>;
}): ExplorerClient {
  const ssr = ssrExchange({ isClient: !import.meta.env.SSR });
  const client = createClient({
    url: "/graphql",
    requestPolicy: "cache-first",
    // urql v5 dedupes in-flight queries internally — no dedupExchange.
    // The introspected schema (generated by codegen from the canonical SDL)
    // gives Graphcache deterministic union/interface handling — SelectionGroupMember
    // is a union; without it, fragment resolution depends on server __typename order (spec/15).
    exchanges: [
      cacheExchange({ schema: schemaJson as unknown as IntrospectionQuery }),
      ssr,
      fetchExchange,
    ],
    fetch: ((input: RequestInfo | URL, init?: RequestInit) => {
      const url =
        opts.origin && typeof input === "string" && input.startsWith("/")
          ? `${opts.origin}${input}`
          : input;
      return fetch(url, {
        ...init,
        headers: { ...Object.fromEntries(new Headers(init?.headers)), ...opts.headers },
      });
    }) as typeof fetch,
  });
  return { client, ssr };
}
